### PR TITLE
Remove ini directives below PATH and HOST sections

### LINKED ISSUE #132: INI file and broken disable_functions
I have an issue, when the copied `ini` file have `proc_open` in `disable_functions`, because of broken merging of additional files. This causes composer to stop working.

#### This is simplified reproduction of this issue:
`php.ini` - default from compilation
```ini
disable_functions=proc_open
```
#### And additional ini files
`01-first.ini` - this contains some rules in `[PATH=..]` section
```ini
[PATH=/var/www/html]
memory_limit=512G
```
`02-second.ini` - this contains rules without sections
```ini
disable_functions=""
```

Composer from these files will produce following `ini` file:
```ini
disable_functions=proc_open
[PATH=/var/www/html]
memory_limit=512G
disable_functions=""
```

As you can see `disable_functions=""` is no longer applicable to all scripts but only to `/var/www/html`. In addition to this also all composer settings are ignored as well, since these are *in* `PATH` section.

### PR DESCRIPTION
**Pull request by johnstevenson**
Fixes #132

### CODE REVIEW

File: src/XdebugHandler.php [hunk 1]
```diff
@@ -377,15 +377,20 @@ private function writeTmpIni(array $iniFiles, $tmpDir, &$error)
...
             if (($data = @file_get_contents($file)) === false) {
                 $error = 'Unable to read ini: '.$file;
                 return false;
             }
-            $content .= preg_replace($regex, ';$1', $data).PHP_EOL;
+            // Check and remove directives after HOST and PATH sections
+            if (preg_match($sectionRegex, $content, $matches, PREG_OFFSET_CAPTURE)) {
+                $content = substr($content, 0, $matches[0][1]);
+            }
+            $content .= preg_replace($xdebugRegex, ';$1', $data).PHP_EOL;
```
Comment (KapitanOczywisty) [inline src/XdebugHandler.php:393]:
```suggestion
            // Check and remove directives after HOST and PATH sections
            if (preg_match($sectionRegex, $data, $matches, PREG_OFFSET_CAPTURE)) {
                $data = substr($data, 0, $matches[0][1]);
            }
            $content .= preg_replace($xdebugRegex, ';$1', $data).PHP_EOL;
```
I think `preg_match/substr` should be done on `$data`, because otherwise the very last file will keep `PATH/HOST` sections and this will mess with the following code:
```php
        // Merge loaded settings into our ini content, if it is valid
        if ($config = parse_ini_string($content)) {
            $loaded = ini_get_all(null, false);
            $content .= $this->mergeLoadedConfig($loaded, $config);
        }

        // Work-around for https://bugs.php.net/bug.php?id=75932
        $content .= 'opcache.enable_cli=0'.PHP_EOL;
```

Comment (johnstevenson) [reply src/XdebugHandler.php:393]: Thanks, good catch, that is pretty sloppy! I'd better check why the test didn't flag it as well.

Comment (KapitanOczywisty) [reply src/XdebugHandler.php:393]: https://github.com/composer/xdebug-handler/blob/c596235e84a1268e5ddb44e1b0c615846d598995/tests/Helpers/IniHelper.php#L69-L79 Loaded just in the right order :)

**Review by KapitanOczywisty — APPROVED** [review]
LGTM Thanks!

**Comment by KapitanOczywisty** [comment]
@johnstevenson When can we expect release with this?

**Comment by johnstevenson** [comment]
I was going to wait until the midde of this month and include the Xdebug 3.1 stuff (which is due for release at the end of this month and should be unlikely to change).

Is that a problem for you?

**Comment by KapitanOczywisty** [comment]
It's just a bit of annoyance to set `XDEBUG_MODE=off` for composer commands, nothing serious. Thanks for the info.
